export class Account{
    accNo:number=0;
    userId:String="";
    userPassword:String="";
    title:String="";
    firstName:String="";
    middleName:String="";
    lastName:String="";
    fatherName:String="";
    mobileNum:number=0;
    emailID:String="";
    aadharNum:number=0;
    dob:String="";
    occType:String="";
    sourceOfIncome:String="";
    grossAnnualIncome:number=0;
    debitCard:number=0;
    netBanking:number=0;
    balance:number=0;
    state:String="";
    landmark:String="";
    city:String="";
    pincode:number=0;
}